name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: Kevin Benton
          GIT_AUTHOR_EMAIL: krbenton@icloud.com
          GIT_COMMITTER_NAME: Kevin Benton
          GIT_COMMITTER_EMAIL: krbenton@icloud.com
        run: yarn multi-semantic-release
